#!/bin/sh
# File generated by ocamlbuild

cd /home/malek/Documents/Project/Zero-Suppressed-Binary-Decision-Diagram

rm -f Project.cmi
# Also clean the script itself
rm -f /home/malek/Documents/Project/Zero-Suppressed-Binary-Decision-Diagram/_build/sanitize.sh
